// Generated by scripts/generate-social-content.mjs. Do not edit manually.
export const latestSocialEdition = {
  "week": "2026-08-17",
  "readyCount": 3,
  "dataUrl": "/social-content/data/2026-08-17.json"
} as const;
export const socialEditionWeeks = [
  "2026-08-17",
  "2026-08-10",
  "2026-08-09",
  "2026-08-03",
  "2026-07-27"
] as const;
